export const Language = [
  {english: 'Notes', hindi: 'टिप्पणियाँ'},
  {english: 'Other', hindi: 'अन्य'},
  {english: 'Pinned', hindi: 'पिन किए गए'},
  {english: 'Search your notes', hindi: 'अपने नोट्स खोजें'},
  {english: 'Reminders', hindi: 'अनुस्मारक'},
  {english: 'Create New Label', hindi: 'नया लेबल बनाएं'},
  {english: 'Archive', hindi: 'पुरालेख'},
  {english: 'Deleted', hindi: 'हटाए गए'},
  {english: 'Settings', hindi: 'समायोजन'},
  {english: 'Help & Feedback', hindi: 'सहायता एवं प्रतिक्रिया'},
  {english: 'Edit labels', hindi: 'लेबल संपादित करें'},
  {english: 'Archived', hindi: 'संग्रहीत'},
  {english: 'SignUp', hindi: 'साइन अप करें'},
  {english: 'Have an account? Login here.', hindi: 'खाता है? यहां लॉगिन करें।'},
  {english: 'Delete', hindi: 'हटाए'},
  {english: 'Make a copy', hindi: 'एक प्रतिलिपि बना लो'},
  {english: 'Send', hindi: 'भेजना'},
  {english: 'Collaborator', hindi: 'सहयोगी'},
  {english: 'Labels', hindi: 'लेबल'},
  {english: 'Enter label name', hindi: 'लेबल नाम दर्ज करें'},
  {english: 'Enter name', hindi: 'नाम दर्ज करें'},
  {english: 'Enter mobile no', hindi: 'मोबाइल नंबर दर्ज करें'},
  {english: 'Enter username', hindi: 'उपयोगकर्ता नाम दर्ज करें'},
  {english: 'Enter password', hindi: 'पास वर्ड दर्ज करें'},
  {english: 'Login', hindi: 'लॉग इन करें'},
  {english: 'Welcome', hindi: 'स्वागत'},
];
